{% set name = "fast-rtps" %}
{% set version = "2.0.0" %}
{% set major_minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/eProsima/Fast-RTPS/archive/v{{ version }}.tar.gz
    sha256: 9be0507d949ada31c296a771a8301740628301a4862fa812a38029c95a2ab418

build:
  number: 0
  skip: true  # [win and vc<14 or unix]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - fast-cdr
    - asio
    - tinyxml2
    - openssl
    - foonathan-memory
  run:
    - fast-cdr
    - asio
    - tinyxml2
    - openssl
    - foonathan-memory

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\bin\\fastrtps-{{ major_minor_version }}.dll exit 1  # [win]

about:
  home: https://github.com/eProsima/Fast-RTPS
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    eProsima Fast RTPS

extra:
  recipe-maintainers:
    - seanyen
