{% set name = "fast-rtps" %}
{% set version = "2.0.0" %}
{% set major_minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/eProsima/Fast-RTPS/archive/v{{ version }}.tar.gz
    sha256: d6003f32592b2ea3b1a544730ddcfe32d020b9961b0b502190af8e80aafe9d01

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - fast-cdr
    - asio
    - tinyxml2
    - openssl
    - foonathan-memory
  run:
    - fast-cdr
    - asio
    - tinyxml2
    - openssl
    - foonathan-memory

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\bin\\fastrtps-{{ major_minor_version }}.dll exit 1  # [win]
    - test -f $PREFIX/lib/libfastrtps${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/fastdds/rtps/Endpoint.h  # [unix]
    - test -f $PREFIX/include/fastrtps/transport/UDPTransportInterface.h  # [unix]

about:
  home: https://github.com/eProsima/Fast-RTPS
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    eProsima Fast RTPS

extra:
  recipe-maintainers:
    - seanyen
